version: '3.8'
name: cleartrack

services:
  api:
    image: api-cleartrack:latest
    environment:
      - SUPABASE_API_URL=http://localhost:54321/rest/v1
      - SUPABASE_URL=http://localhost:54321
      - NODE_ENV=development
      - PORT=3000
      # Update the following key with your own Supabase key. This one is only valid for my local development and it's too convenient to change it.
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
    build:
      context: ./backend/api
      # Comment this line if you are building for production?
      target: development-stage
    ports:
      - 3000:3000
    networks:
      - cleartrack
    volumes:
      - ./backend/api:/app
      - /app/node_modules/

  frontend:
    image: frontend-cleartrack:latest
    environment:
      - VITE_SUPABASE_PROJECT_KEY=localhost
      - VITE_SUPABASE_URL=http://localhost:54321
      - VITE_SUPABASE_REDIRECT_URL=http://cleartrack.localhost/auth/callback
      - VITE_PROXY_URL=http://cleartrack.localhost/api/v1/
      # Update the following key with your own Supabase key. This one is only valid for my local development and it's too convenient to change it.
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
    build: 
      context: ./frontend
      target: development-stage
    ports:
      - 5173:5173
    networks:
      - cleartrack
    volumes:
      - ./frontend:/app
      - /app/node_modules/

  nginx:
    image: nginx-cleartrack:latest
    build: ./backend/nginx
    ports:
      - 80:80
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cleartrack
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      - api
      - frontend

networks:
  cleartrack:
    driver: bridge
