create table "public"."project_stakeholders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "department_id" bigint,
    "stakeholder_type" text
);

alter table "public"."project_stakeholders" enable row level security;

create table "public"."stakeholder_department" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "stakeholder_name" text,
    "department_id" bigint,
    "role" text
);


alter table "public"."stakeholder_department" enable row level security;

alter table "public"."management_response_actions" drop column "Date_Recommendation_Closed";

alter table "public"."management_response_actions" drop column "Latest_approved_completion_date";

alter table "public"."management_response_actions" drop column "Link_to_MRAP";

alter table "public"."management_response_actions" drop column "Recommendation_EN";

alter table "public"."management_response_actions" drop column "Recommendation_FR";

alter table "public"."management_response_actions" drop column "Recommendation_Level";

alter table "public"."recommendations" drop column "body";

alter table "public"."recommendations" add column "comments" text;

alter table "public"."recommendations" add column "date_closed" timestamp with time zone;

alter table "public"."recommendations" add column "how_late" timestamp with time zone;

alter table "public"."recommendations" add column "latest_approved_completion_date" timestamp with time zone;

alter table "public"."recommendations" add column "level" "Recommendation_Level";

alter table "public"."recommendations" add column "link_to_rec_mrap" character varying;

alter table "public"."recommendations" add column "recommendation_EN" text;

alter table "public"."recommendations" add column "recommendation_FR" text;

CREATE UNIQUE INDEX "Project_Stakeholders_pkey" ON public.project_stakeholders USING btree (id);

CREATE UNIQUE INDEX stakeholder_department_pkey ON public.stakeholder_department USING btree (id);

alter table "public"."project_stakeholders" add constraint "Project_Stakeholders_pkey" PRIMARY KEY using index "Project_Stakeholders_pkey";

alter table "public"."stakeholder_department" add constraint "stakeholder_department_pkey" PRIMARY KEY using index "stakeholder_department_pkey";

grant delete on table "public"."project_stakeholders" to "anon";

grant insert on table "public"."project_stakeholders" to "anon";

grant references on table "public"."project_stakeholders" to "anon";

grant select on table "public"."project_stakeholders" to "anon";

grant trigger on table "public"."project_stakeholders" to "anon";

grant truncate on table "public"."project_stakeholders" to "anon";

grant update on table "public"."project_stakeholders" to "anon";

grant delete on table "public"."project_stakeholders" to "authenticated";

grant insert on table "public"."project_stakeholders" to "authenticated";

grant references on table "public"."project_stakeholders" to "authenticated";

grant select on table "public"."project_stakeholders" to "authenticated";

grant trigger on table "public"."project_stakeholders" to "authenticated";

grant truncate on table "public"."project_stakeholders" to "authenticated";

grant update on table "public"."project_stakeholders" to "authenticated";

grant delete on table "public"."project_stakeholders" to "service_role";

grant insert on table "public"."project_stakeholders" to "service_role";

grant references on table "public"."project_stakeholders" to "service_role";

grant select on table "public"."project_stakeholders" to "service_role";

grant trigger on table "public"."project_stakeholders" to "service_role";

grant truncate on table "public"."project_stakeholders" to "service_role";

grant update on table "public"."project_stakeholders" to "service_role";

grant delete on table "public"."stakeholder_department" to "anon";

grant insert on table "public"."stakeholder_department" to "anon";

grant references on table "public"."stakeholder_department" to "anon";

grant select on table "public"."stakeholder_department" to "anon";

grant trigger on table "public"."stakeholder_department" to "anon";

grant truncate on table "public"."stakeholder_department" to "anon";

grant update on table "public"."stakeholder_department" to "anon";

grant delete on table "public"."stakeholder_department" to "authenticated";

grant insert on table "public"."stakeholder_department" to "authenticated";

grant references on table "public"."stakeholder_department" to "authenticated";

grant select on table "public"."stakeholder_department" to "authenticated";

grant trigger on table "public"."stakeholder_department" to "authenticated";

grant truncate on table "public"."stakeholder_department" to "authenticated";

grant update on table "public"."stakeholder_department" to "authenticated";

grant delete on table "public"."stakeholder_department" to "service_role";

grant insert on table "public"."stakeholder_department" to "service_role";

grant references on table "public"."stakeholder_department" to "service_role";

grant select on table "public"."stakeholder_department" to "service_role";

grant trigger on table "public"."stakeholder_department" to "service_role";

grant truncate on table "public"."stakeholder_department" to "service_role";

grant update on table "public"."stakeholder_department" to "service_role";


