revoke delete on table "public"."project_stakeholders" from "anon";

revoke insert on table "public"."project_stakeholders" from "anon";

revoke references on table "public"."project_stakeholders" from "anon";

revoke select on table "public"."project_stakeholders" from "anon";

revoke trigger on table "public"."project_stakeholders" from "anon";

revoke truncate on table "public"."project_stakeholders" from "anon";

revoke update on table "public"."project_stakeholders" from "anon";

revoke delete on table "public"."project_stakeholders" from "authenticated";

revoke insert on table "public"."project_stakeholders" from "authenticated";

revoke references on table "public"."project_stakeholders" from "authenticated";

revoke select on table "public"."project_stakeholders" from "authenticated";

revoke trigger on table "public"."project_stakeholders" from "authenticated";

revoke truncate on table "public"."project_stakeholders" from "authenticated";

revoke update on table "public"."project_stakeholders" from "authenticated";

revoke delete on table "public"."project_stakeholders" from "service_role";

revoke insert on table "public"."project_stakeholders" from "service_role";

revoke references on table "public"."project_stakeholders" from "service_role";

revoke select on table "public"."project_stakeholders" from "service_role";

revoke trigger on table "public"."project_stakeholders" from "service_role";

revoke truncate on table "public"."project_stakeholders" from "service_role";

revoke update on table "public"."project_stakeholders" from "service_role";

alter table "public"."recommendations" drop constraint "public_recommendations_id_fkey";

alter table "public"."project_stakeholders" drop constraint "Project_Stakeholders_pkey";

drop index if exists "public"."Project_Stakeholders_pkey";

drop table "public"."project_stakeholders";

create table "public"."departments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "updated_at" timestamp with time zone
);


alter table "public"."departments" enable row level security;

create table "public"."project_stakeholder" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "project_id" bigint,
    "stakeholder_id" bigint
);


alter table "public"."project_stakeholder" enable row level security;

create table "public"."stakeholders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "stakeholder_type" text not null,
    "name" text not null
);


alter table "public"."stakeholders" enable row level security;

alter table "public"."project_types" enable row level security;

alter table "public"."recommendations" add column "project_id" bigint;

alter table "public"."resources" add column "status" boolean not null default true;

CREATE UNIQUE INDEX departments_pkey ON public.departments USING btree (id);

CREATE UNIQUE INDEX project_department_pkey ON public.project_stakeholder USING btree (id);

CREATE UNIQUE INDEX "Project_Stakeholders_pkey" ON public.stakeholders USING btree (id);

alter table "public"."departments" add constraint "departments_pkey" PRIMARY KEY using index "departments_pkey";

alter table "public"."project_stakeholder" add constraint "project_department_pkey" PRIMARY KEY using index "project_department_pkey";

alter table "public"."stakeholders" add constraint "Project_Stakeholders_pkey" PRIMARY KEY using index "Project_Stakeholders_pkey";

alter table "public"."project_stakeholder" add constraint "public_project_department_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."project_stakeholder" validate constraint "public_project_department_project_id_fkey";

alter table "public"."project_stakeholder" add constraint "public_project_stakeholder_stakeholder_id_fkey" FOREIGN KEY (stakeholder_id) REFERENCES stakeholders(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."project_stakeholder" validate constraint "public_project_stakeholder_stakeholder_id_fkey";

alter table "public"."recommendations" add constraint "public_recommendations_project_id_fkey" FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."recommendations" validate constraint "public_recommendations_project_id_fkey";

alter table "public"."stakeholder_department" add constraint "public_stakeholder_department_department_id_fkey" FOREIGN KEY (department_id) REFERENCES departments(id) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."stakeholder_department" validate constraint "public_stakeholder_department_department_id_fkey";

grant delete on table "public"."departments" to "anon";

grant insert on table "public"."departments" to "anon";

grant references on table "public"."departments" to "anon";

grant select on table "public"."departments" to "anon";

grant trigger on table "public"."departments" to "anon";

grant truncate on table "public"."departments" to "anon";

grant update on table "public"."departments" to "anon";

grant delete on table "public"."departments" to "authenticated";

grant insert on table "public"."departments" to "authenticated";

grant references on table "public"."departments" to "authenticated";

grant select on table "public"."departments" to "authenticated";

grant trigger on table "public"."departments" to "authenticated";

grant truncate on table "public"."departments" to "authenticated";

grant update on table "public"."departments" to "authenticated";

grant delete on table "public"."departments" to "service_role";

grant insert on table "public"."departments" to "service_role";

grant references on table "public"."departments" to "service_role";

grant select on table "public"."departments" to "service_role";

grant trigger on table "public"."departments" to "service_role";

grant truncate on table "public"."departments" to "service_role";

grant update on table "public"."departments" to "service_role";

grant delete on table "public"."project_stakeholder" to "anon";

grant insert on table "public"."project_stakeholder" to "anon";

grant references on table "public"."project_stakeholder" to "anon";

grant select on table "public"."project_stakeholder" to "anon";

grant trigger on table "public"."project_stakeholder" to "anon";

grant truncate on table "public"."project_stakeholder" to "anon";

grant update on table "public"."project_stakeholder" to "anon";

grant delete on table "public"."project_stakeholder" to "authenticated";

grant insert on table "public"."project_stakeholder" to "authenticated";

grant references on table "public"."project_stakeholder" to "authenticated";

grant select on table "public"."project_stakeholder" to "authenticated";

grant trigger on table "public"."project_stakeholder" to "authenticated";

grant truncate on table "public"."project_stakeholder" to "authenticated";

grant update on table "public"."project_stakeholder" to "authenticated";

grant delete on table "public"."project_stakeholder" to "service_role";

grant insert on table "public"."project_stakeholder" to "service_role";

grant references on table "public"."project_stakeholder" to "service_role";

grant select on table "public"."project_stakeholder" to "service_role";

grant trigger on table "public"."project_stakeholder" to "service_role";

grant truncate on table "public"."project_stakeholder" to "service_role";

grant update on table "public"."project_stakeholder" to "service_role";

grant delete on table "public"."stakeholders" to "anon";

grant insert on table "public"."stakeholders" to "anon";

grant references on table "public"."stakeholders" to "anon";

grant select on table "public"."stakeholders" to "anon";

grant trigger on table "public"."stakeholders" to "anon";

grant truncate on table "public"."stakeholders" to "anon";

grant update on table "public"."stakeholders" to "anon";

grant delete on table "public"."stakeholders" to "authenticated";

grant insert on table "public"."stakeholders" to "authenticated";

grant references on table "public"."stakeholders" to "authenticated";

grant select on table "public"."stakeholders" to "authenticated";

grant trigger on table "public"."stakeholders" to "authenticated";

grant truncate on table "public"."stakeholders" to "authenticated";

grant update on table "public"."stakeholders" to "authenticated";

grant delete on table "public"."stakeholders" to "service_role";

grant insert on table "public"."stakeholders" to "service_role";

grant references on table "public"."stakeholders" to "service_role";

grant select on table "public"."stakeholders" to "service_role";

grant trigger on table "public"."stakeholders" to "service_role";

grant truncate on table "public"."stakeholders" to "service_role";

grant update on table "public"."stakeholders" to "service_role";

create policy "Enable read access for all users"
on "public"."departments"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_resource"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."project_stakeholder"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."projects"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."recommendations"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."stakeholder_department"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."stakeholders"
as permissive
for select
to public
using (true);



